apiVersion: v1
entries:
  application-gateway-kubernetes-ingress:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-11T12:20:42.6822992-07:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: bad552d53a56bb4d35b34de049ed0d8ee320ad31b5919c6b7b18dc795d4881f2
    name: application-gateway-kubernetes-ingress
    urls:
    - https://azure.github.io/application-gateway-kubernetes-ingress/helm/application-gateway-kubernetes-ingress-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-11T12:20:42.6822992-07:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: 2b69c2ce65458c1e8536abc83629cd7ccc0bc422a81e93c1a198e80ce7666ebd
    name: application-gateway-kubernetes-ingress
    urls:
    - https://azure.github.io/application-gateway-kubernetes-ingress/helm/application-gateway-kubernetes-ingress-0.1.0.tgz
    version: 0.1.0
generated: 2018-09-11T12:20:42.6813292-07:00
