apiVersion: v1
entries:
  ingress-azure:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-13T12:43:02.1802783-07:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: 9664986a6affd3487d5a41772c7e92b23d79693e89d37143e094fec0fbcec1c2
    name: ingress-azure
    urls:
    - https://azure.github.io/application-gateway-kubernetes-ingress/helm/ingress-azure-0.1.2.tgz
    version: 0.1.2
generated: 2018-09-13T12:43:02.1792823-07:00
